### ISSUE TITLE
trailing_comma_in_multiline - macht Probleme

### ISSUE THREAD

**Issue by aeberhard** [redaxo/php-cs-fixer-config#1]
aus folgendem Code

```
    $sql->setQuery('SELECT `start_lang`.uid, `start_lang`.script FROM `'. rex::getTablePrefix() .'consent_manager_cookie` AS `start_lang` '
        . 'LEFT JOIN `'. rex::getTablePrefix() .'consent_manager_cookie` AS `other_lang` ON `start_lang`.uid = `other_lang`.uid '
        . 'WHERE `start_lang`.clang_id = '. rex_clang::getStartId() ." AND `start_lang`.script <> '' AND `other_lang`.script = '' "
        . 'GROUP BY uid, script');
```

wird

```
    $sql->setQuery('SELECT `start_lang`.uid, `start_lang`.script FROM `'. rex::getTablePrefix() .'consent_manager_cookie` AS `start_lang` '
        . 'LEFT JOIN `'. rex::getTablePrefix() .'consent_manager_cookie` AS `other_lang` ON `start_lang`.uid = `other_lang`.uid '
        . 'WHERE `start_lang`.clang_id = '. rex_clang::getStartId() ." AND `start_lang`.script <> '' AND `other_lang`.script = '' "
        . 'GROUP BY uid, script', );
```

also am Ende wird noch ein `,` eingefügt, was ja in diesem Fall falsch ist.

```
        'trailing_comma_in_multiline' => [
            'after_heredoc' => true,
            'elements' => ['arguments', 'arrays', 'match', 'parameters'],
        ],
```

Wenn ich `arguments` aus obigen Parametern entferne dann ist alles gut und kein Komma wird eingefügt

**Comment by aeberhard** [comment]
@gharlan 
Ich habe die aktuellen config-Werte auf Windows übernommen. 
Ausführung des Fixers mit PHP 8.0.26 falls das eine Rolle spielen sollte.

**Comment by aeberhard** [comment]
Hier noch die komplette Datei in der das `arguments` noch drin ist

https://github.com/FriendsOfREDAXO/demo_fullpage/blob/main/.php-cs-fixer.dist.php

**Comment by gharlan** [comment]
Mir ist auch schon aufgefallen, dass der Fixer teils nicht ganz optimale Ergebnisse liefert (wobei es trotzdem gültiger Code ist, nur nicht schön). Ich will mir das irgendwann mal direkt im CS-Fixer anschauen, kann aber nichts versprechen, wann ich dazu komme.

Ich würde den Code allerdings eher so schreiben:

```php
$sql->setQuery('
    SELECT `start_lang`.uid, `start_lang`.script FROM `'. rex::getTablePrefix() .'consent_manager_cookie` AS `start_lang`
    LEFT JOIN `'. rex::getTablePrefix() .'consent_manager_cookie` AS `other_lang` ON `start_lang`.uid = `other_lang`.uid
    WHERE `start_lang`.clang_id = '. rex_clang::getStartId() .' AND `start_lang`.script <> "" AND `other_lang`.script = ""
    GROUP BY uid, script
');
```

Und da entsteht dann das Problem nicht.

**Comment by aeberhard** [comment]
Probiere ich mal aus @gharlan.

Wie wird denn der Fixer in REDAXO eingebunden? Kann man das evtl. auch bei den FOR-AddOns (optional) verwenden!?

**Comment by gharlan** [comment]
Wir laden das Paket über Composer und nutzen es dann in der `.php-cs-fixer.dist.php` (siehe Core-Repo, bzw. Readme hier im Repo).

Müsste so in der Art auch in Addons gehen.

**Comment by aeberhard** [comment]
Ich habe jetzt mal das **REPO** in VSCode eingebunden und werde weiter testen und berichten (wenns recht ist :))

https://friendsofredaxo.github.io/tricks/development/editor-vscode

Dabei ist mir aufgefallen dass auch noch die Custom Fixers benötigt werden!? https://github.com/kubawerlos/php-cs-fixer-custom-fixers/

Sehe ich das richtig!?

Sonst ist bisher alles gut ... einen neuen "Bug" habe ich evtl. gefunden #2 

@gharlan @staabm

**Comment by gharlan** [comment]
> Dabei ist mir aufgefallen dass auch noch die Custom Fixers benötigt werden!? [kubawerlos/php-cs-fixer-custom-fixers](https://github.com/kubawerlos/php-cs-fixer-custom-fixers/)

Ja, das Paket ist [eine Abhängigkeit hier im Repo](https://github.com/redaxo/php-cs-fixer-config/blob/1ae3fd293e43b40885a96bb30b9883d86fdf44f9/composer.json#L15). (über composer wird es somit automatisch mitgeladen)

**Comment by aeberhard** [comment]
Ich mach hier mal zu, für mich passt das jetzt mit dem angepassten setQuery.
