### ISSUE TITLE
'@PHP80Migration:risky' => true erzeugt Code den rexstan gar nicht mag 

### ISSUE THREAD

**Issue by aeberhard** [redaxo/php-cs-fixer-config#2]
Den folgenden Code mag **rexstan** und klappt auch wunderbar.

```php
        // Erste H2 durch H1 ersetzen wenn kein H1 vorhanden ist
        if ('|1|' === $addon->getConfig('converth2')) {
            if (false === strpos($content, '<h1') && false === strpos($content, '/h1>')) {
                if (false !== strpos($content, '<h2') && false !== strpos($content, '/h2>')) {
                    $content = substr_replace($content, '<h1', strpos($content, '<h2'), strlen('<h2'));
                    if (false !== strpos($content, '<h2') && false !== strpos($content, '/h2>')) {
                        $content = substr_replace($content, '/h1>', strpos($content, '/h2>'), strlen('/h2>'));
                    }
                }
            }
        }
```

Mit den REDAXO-Coding-Standards wird folgender Code daraus ...

```php
        // Erste H2 durch H1 ersetzen wenn kein H1 vorhanden ist
        if ('|1|' === $addon->getConfig('converth2')) {
            if (!str_contains($content, '<h1') && !str_contains($content, '/h1>')) {
                if (str_contains($content, '<h2') && str_contains($content, '/h2>')) {
                    $content = substr_replace($content, '<h1', strpos($content, '<h2'), strlen('<h2'));
                    if (str_contains($content, '<h2') && str_contains($content, '/h2>')) {
                        $content = substr_replace($content, '/h1>', strpos($content, '/h2>'), strlen('/h2>'));
                    }
                }
            }
        }
```

Und sowas `!str_contains($content, '<h1')` ist ja laut **rexstan** _**böse**_ 

Mit Tante G bin ich dann auf folgende Seite gestossen
https://cs.symfony.com/doc/rules/alias/modernize_strpos.html

Wenn ich also `'@PHP80Migration:risky' => false` setze wird auch nicht `str_contains` "reingesetzt".

@gharlan @staabm

**Comment by gharlan** [comment]
Wie lautet die rexstan-Meldung?
Welche PHP-Version nutzt du? (die aktuelle Version unserer php-cs-fixer-Config erfordert PHP 8.1, so wie auch das redaxo-Hauptrepo inzwischen)

**Comment by aeberhard** [comment]
Verwendet wird PHP 8.2.0, auch bei den rexstan-Einstellungen

Der Code mit strpos wird nicht angemeckert und funktioniert. Der Ersetzte Code meldet folgendes in rexstan.

Code mit str_contains funktioniert aber auch wie erwartet.

```
147:Parameter #3 $offset of function substr_replace expects array|int, int<0, max>|false given.
149:Parameter #3 $offset of function substr_replace expects array|int, int<0, max>|false given.
```

**Comment by aeberhard** [comment]
Jetzt bin ich durch **rexstan** drauf angefixt `!function(HasteNichtGesehen)` nicht zu verwenden, sondern immer mit 
z.B. `false === function(HasteNichtGesehen)` zu verwenden und dann sowas 
:)))

**Comment by gharlan** [comment]
Das kommt auf die Function an. Bei `strpos` ist es wichtig, mit `false` zu vergleichen, weil `strpos` ja auch `0` liefern kann.
Bei `str_contains` aber zum Beispiel kommt nur true/false zurück, somit kann man da bedenkenlos mit `!str_containts` arbeiten.

Hier habe ich versucht die Problematik mit reduziertem Code und Kommentaren deutlich zu machen:
https://phpstan.org/r/8eafff97-46af-4b17-a3ef-8d60bd1e4d5e
Wie dort angedeutet, würde ich die Position in eine Variable packen, wenn sie später erneut gebraucht wird. Und dann sollte der CS-Fixer die Stelle auch nicht ändern.

Ansonsten wollen wir den Fixer aber bewusst nutzen. Also strpos-Stellen sollen bewusst in str_contains umgewandelt werden, wenn die Position gar nicht verwendet wird, sondern nur geprüft wird, ob ein String vorkommt.
str_contains wurde ja in PHP 8 bewusst ergänzt, weil es für den Zweck besser geeignet ist (besser lesbar, keine 0/false-Problematik, vermutlich performanter).
