### ISSUE TITLE
modernize strpos

### ISSUE THREAD

**Issue by staabm** [redaxo/php-cs-fixer-config#5]
da der redaxo core die polyfills für str_starts_with, str_contains etc. mitbringt, sollten wir `'modernize_strpos' => true` in den redaxo rules definieren.

damit hätte man besser lesbaren code und aufgrund der poyfill eigentlich auch keine probleme.

https://cs.symfony.com/doc/rules/alias/modernize_strpos.html

**Comment by gharlan** [comment]
Müsste bereits aktiv sein, da wir `@PHP80Migration:risky` aktiviert haben.
https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/blob/master/src/RuleSet/Sets/PHP80MigrationRiskySet.php#L29

**Comment by gharlan** [comment]
Ich habe es gerade mal im Core-Repo getestet, dort wird es auch korrekt angewandt.

**Comment by staabm** [comment]
hmm ohne explizit aktivieren funktioniert es im rexfactor nicht: 

https://github.com/FriendsOfREDAXO/rexfactor/pull/54/files

**Comment by gharlan** [comment]
rexfactor nutzt redaxo/php-cs-fixer-config 1.x, aktuell ist aber 2.1.1

**Comment by staabm** [comment]
ahh.. die php-cs-fixer-config setzt php 8.1 vorraus. daher hat composer bei mir 1.x gezogen

**Comment by staabm** [comment]
gibts einen grund für die hohe php mindest version? die 2 cs-fixer externals wären auch mit 7.4 zufrieden

**Comment by gharlan** [comment]
Ich hatte die Version auf 8.1 gesetzt, weil ich die 8.1-Migration-Sets aktiviert hatte.

Beim PHP-CS-Fixer ist es so, dass man keine PHP-Zielversion einstellen kann. Zielversion ist immer die aktuelle Runtime.
Wobei die Fixer meist Version-Checks enthalten, und wenn Runtime kleiner, dann machen die Fixer nix.
Somit wäre es wahrscheinlich eigentlich kein Problem, mit PHP 7.4 die 8.1-Migrations laufen zu lassen, da die dann nichts machen würden.
Problem ist aber, wenn jemand ein Addon für 7.4 entwickelt, aber lokal gerade PHP 8.x aktiv hat. Dann produziert die Config 2.x entsprechend 8.1-Code, der ggf. nicht mehr zu 7.4 kompatibel ist.

Beispiel: du hast bei dir gerade PHP 8.1 aktiv und lässt die config 2.x auf das rexfactor-Addon los. Danach ist der Code eventuell nicht mehr zu 7.4 kompatibel.

Daher hatte ich eine klare neue Min-PHP-Version gesetzt entsprechend der verwendeten Fixer, um es einheitlich zu haben.

Ich verstehe die Problematik für rexfactor. Weiß aber noch nicht recht, wie wir das lösen können.

**Comment by staabm** [comment]
ok. ich werde dann in rexfactor weiterhin cs-fixer 1.x verwenden und versuchen alle fixer zu aktivieren die php 7.4 kompatibel sind
