### ISSUE TITLE
Style für Concat-Operator festlegen?

### ISSUE THREAD

**Issue by gharlan** [redaxo/php-cs-fixer-config#6]
Ursprünglich hatten wir bei REDAXO mal Leerzeichen drum rum verlangt: `$foo . 'bar'`
Dann hatte ich bei uns aber den Symfony-Style als Basis genommen, und dort sind sie verboten, somit: `$foo.'bar'`.
Da ich mir dabei aber unsicher war, und mir die Änderung im Core-Repo damals zu groß war, habe ich dann stattdessen die Rule erstmal ganz deaktiviert.
Und so ist es bis heute geblieben, also aktuell sind bei uns beide Varianten erlaubt.

In meinen eigenen Symfony-Projekten nutze ich allerdings `$foo.'bar'` und habe mich dran gewöhnt. Daher verwende ich es auch meist in neuem Code für REDAXO.
Eigentlich wäre aber `$foo . 'bar'` durchaus logisch, weil die anderen binären Operatoren auch Leerzeichen drum rum bekommen (`$foo + 2`).
Auch PHP-Fig erfordert aktuell Leerzeichen beim Concat-Operator (String-Operatoren): https://www.php-fig.org/per/coding-style/#62-binary-operators

Also was machen?
1. So lassen, beides bleibt erlaubt
2. Einheitlich `$foo . 'bar'`
3. Einheitlich `$foo.'bar'`

**Comment by gharlan** [comment]
@staabm hast du hier eine Meinung zu?

Hier kann ich mit allen drei Varianten leben, bin aber eigentlich für Einheitlichkeit. Somit 2 oder 3. Zwischen denen kann ich mich aber nicht recht entscheiden.

**Comment by staabm** [comment]
Ich mag 2. bin auch mit 3 ok

**Comment by aeberhard** [comment]
> Eigentlich wäre aber $foo . 'bar' durchaus logisch, weil die anderen binären Operatoren auch Leerzeichen drum rum bekommen ($foo + 2).

also ich bin auch bei 2 :)
